bullseye has been EOL
```
 INFO :     package[git] installed will change from 'false' to 'true'
ERROR :       stdout | Reading package lists...
ERROR :       stdout | Building dependency tree...
ERROR :       stdout | Reading state information...
ERROR :       stdout | The following additional packages will be installed:
ERROR :       stdout |   ca-certificates git-man less libbrotli1 libbsd0 libcbor0 libcurl3-gnutls
ERROR :       stdout |   libedit2 liberror-perl libexpat1 libfido2-1 libgdbm-compat4 libgdbm6
ERROR :       stdout |   libldap-2.4-2 libldap-common libmd0 libnghttp2-14 libperl5.32 libpsl5
ERROR :       stdout |   librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 libx11-6
ERROR :       stdout |   libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 netbase
ERROR :       stdout |   openssh-client openssl patch perl perl-modules-5.32 publicsuffix xauth
ERROR :       stdout | Suggested packages:
ERROR :       stdout |   gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
ERROR :       stdout |   git-gui gitk gitweb git-cvs git-mediawiki git-svn gdbm-l10n sensible-utils
ERROR :       stdout |   libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
ERROR :       stdout |   libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql keychain
ERROR :       stdout |   libpam-ssh monkeysphere ssh-askpass ed diffutils-doc perl-doc
ERROR :       stdout |   libterm-readline-gnu-perl | libterm-readline-perl-perl make
ERROR :       stdout |   libtap-harness-archive-perl
ERROR :       stdout | The following NEW packages will be installed:
ERROR :       stdout |   ca-certificates git git-man less libbrotli1 libbsd0 libcbor0 libcurl3-gnutls
ERROR :       stdout |   libedit2 liberror-perl libexpat1 libfido2-1 libgdbm-compat4 libgdbm6
ERROR :       stdout |   libldap-2.4-2 libldap-common libmd0 libnghttp2-14 libperl5.32 libpsl5
ERROR :       stdout |   librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 libx11-6
ERROR :       stdout |   libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 netbase
ERROR :       stdout |   openssh-client openssl patch perl perl-modules-5.32 publicsuffix xauth
ERROR :       stdout | 0 upgraded, 40 newly installed, 0 to remove and 0 not upgraded.
ERROR :       stdout | Need to get 20.5 MB of archives.
ERROR :       stdout | After this operation, 102 MB of additional disk space will be used.
ERROR :       stdout | Get:1 http://deb.debian.org/debian-security bullseye-security/main amd64 perl-modules-5.32 all 5.32.1-4+deb11u5 [2823 kB]
ERROR :       stdout | Get:2 http://deb.debian.org/debian bullseye/main amd64 libgdbm6 amd64 1.19-2 [64.9 kB]
ERROR :       stdout | Get:3 http://deb.debian.org/debian bullseye/main amd64 libgdbm-compat4 amd64 1.19-2 [44.7 kB]
ERROR :       stdout | Err:4 http://deb.debian.org/debian-security bullseye-security/main amd64 libperl5.32 amd64 5.32.1-4+deb11u5
ERROR :       stdout |   404  Not Found [IP: 146.75.30.132 80]
ERROR :       stdout | Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 perl amd64 5.32.1-4+deb11u5 [294 kB]
ERROR :       stdout | Get:6 http://deb.debian.org/debian bullseye/main amd64 less amd64 551-2+deb11u2 [136 kB]
ERROR :       stdout | Get:7 http://deb.debian.org/debian bullseye/main amd64 netbase all 6.3 [19.9 kB]
ERROR :       stdout | Get:8 http://deb.debian.org/debian-security bullseye-security/main amd64 openssl amd64 1.1.1w-0+deb11u8 [860 kB]
ERROR :       stdout | Get:9 http://deb.debian.org/debian-security bullseye-security/main amd64 ca-certificates all 20250419~deb12u1~deb11u1 [175 kB]
ERROR :       stdout | Get:10 http://deb.debian.org/debian bullseye/main amd64 libmd0 amd64 1.0.3-3 [28.0 kB]
ERROR :       stdout | Get:11 http://deb.debian.org/debian bullseye/main amd64 libbsd0 amd64 0.11.3-1+deb11u1 [108 kB]
ERROR :       stdout | Get:12 http://deb.debian.org/debian bullseye/main amd64 libedit2 amd64 3.1-20191231-2+b1 [96.7 kB]
ERROR :       stdout | Get:13 http://deb.debian.org/debian bullseye/main amd64 libcbor0 amd64 0.5.0+dfsg-2 [24.0 kB]
ERROR :       stdout | Get:14 http://deb.debian.org/debian bullseye/main amd64 libfido2-1 amd64 1.6.0-2 [53.3 kB]
ERROR :       stdout | Get:15 http://deb.debian.org/debian-security bullseye-security/main amd64 openssh-client amd64 1:8.4p1-5+deb11u7 [934 kB]
ERROR :       stdout | Get:16 http://deb.debian.org/debian bullseye/main amd64 libbrotli1 amd64 1.0.9-2+b2 [279 kB]
ERROR :       stdout | Get:17 http://deb.debian.org/debian bullseye/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-2.1+deb11u1 [69.1 kB]
ERROR :       stdout | Get:18 http://deb.debian.org/debian bullseye/main amd64 libsasl2-2 amd64 2.1.27+dfsg-2.1+deb11u1 [106 kB]
ERROR :       stdout | Get:19 http://deb.debian.org/debian bullseye/main amd64 libldap-2.4-2 amd64 2.4.57+dfsg-3+deb11u1 [232 kB]
ERROR :       stdout | Get:20 http://deb.debian.org/debian-security bullseye-security/main amd64 libnghttp2-14 amd64 1.43.0-1+deb11u3 [77.6 kB]
ERROR :       stdout | Get:21 http://deb.debian.org/debian bullseye/main amd64 libpsl5 amd64 0.21.0-1.2 [57.3 kB]
ERROR :       stdout | Get:22 http://deb.debian.org/debian bullseye/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2+b2 [60.8 kB]
ERROR :       stdout | Get:23 http://deb.debian.org/debian bullseye/main amd64 libssh2-1 amd64 1.9.0-2+deb11u1 [156 kB]
ERROR :       stdout | Get:24 http://deb.debian.org/debian-security bullseye-security/main amd64 libcurl3-gnutls amd64 7.74.0-1.3+deb11u16 [344 kB]
ERROR :       stdout | Get:25 http://deb.debian.org/debian-security bullseye-security/main amd64 libexpat1 amd64 2.2.10-2+deb11u7 [99.2 kB]
ERROR :       stdout | Get:26 http://deb.debian.org/debian bullseye/main amd64 liberror-perl all 0.17029-1 [31.0 kB]
ERROR :       stdout | Get:27 http://deb.debian.org/debian-security bullseye-security/main amd64 git-man all 1:2.30.2-1+deb11u5 [1831 kB]
ERROR :       stdout | Get:28 http://deb.debian.org/debian-security bullseye-security/main amd64 git amd64 1:2.30.2-1+deb11u5 [5568 kB]
ERROR :       stdout | Get:29 http://deb.debian.org/debian bullseye/main amd64 libldap-common all 2.4.57+dfsg-3+deb11u1 [95.8 kB]
ERROR :       stdout | Get:30 http://deb.debian.org/debian bullseye/main amd64 libsasl2-modules amd64 2.1.27+dfsg-2.1+deb11u1 [104 kB]
ERROR :       stdout | Get:31 http://deb.debian.org/debian bullseye/main amd64 libxau6 amd64 1:1.0.9-1 [19.7 kB]
ERROR :       stdout | Get:32 http://deb.debian.org/debian bullseye/main amd64 libxdmcp6 amd64 1:1.1.2-3 [26.3 kB]
ERROR :       stdout | Get:33 http://deb.debian.org/debian bullseye/main amd64 libxcb1 amd64 1.14-3 [140 kB]
ERROR :       stdout | Get:34 http://deb.debian.org/debian bullseye/main amd64 libx11-data all 2:1.7.2-1+deb11u2 [311 kB]
ERROR :       stdout | Get:35 http://deb.debian.org/debian bullseye/main amd64 libx11-6 amd64 2:1.7.2-1+deb11u2 [772 kB]
ERROR :       stdout | Get:36 http://deb.debian.org/debian bullseye/main amd64 libxext6 amd64 2:1.3.3-1.1 [52.7 kB]
ERROR :       stdout | Get:37 http://deb.debian.org/debian bullseye/main amd64 libxmuu1 amd64 2:1.1.2-2+b3 [23.9 kB]
ERROR :       stdout | Get:38 http://deb.debian.org/debian bullseye/main amd64 patch amd64 2.7.6-7 [128 kB]
ERROR :       stdout | Get:39 http://deb.debian.org/debian bullseye/main amd64 publicsuffix all 20220811.1734-0+deb11u1 [127 kB]
ERROR :       stdout | Get:40 http://deb.debian.org/debian bullseye/main amd64 xauth amd64 1:1.1-1 [40.5 kB]
ERROR :       stdout | Fetched 16.4 MB in 0s (104 MB/s)
ERROR :       stderr | E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/p/perl/libperl5.32_5.32.1-4%2bdeb11u5_amd64.deb  404  Not Found [IP: 146.75.30.132 80]
ERROR :       stderr | E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR :       Command `DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold'  install git` failed. (exit status: 100)
ERROR :     package[git] Failed.
Error: Process completed with exit code 2.
```

Close #74